sharedWith: []
status: public
allowDomain: []

workspaces:
  activateOnStart:
    - Telegram Bot Admin Panel
  Telegram Bot Admin Panel:
    title: Telegram Bot and Admin Panel
    type: split-vertical
    splits:
      layout: 50
      limit:
        - Start application
      0:
        runMainOnStart: true
      1:
        workspaces:
          activateOnStart:
            - Telegram Bot
          Telegram Bot:
            title: Telegram Bot
            type: basic
            command: python working_telegram_bot.py